print("")
print("  _                     _     _             _             _                    ")
print(" | |__   ___ _ __ _ __ (_)___| |_ _ __ __ _| |_ ___  __ _(_) ___   _ __  _   _ ")
print(" | '_ \ / _ \ '__| '_ \| / __| __| '__/ _` | __/ _ \/ _` | |/ _ \ | '_ \| | | |")
print(" | | | |  __/ |  | | | | \__ \ |_| | | (_| | ||  __/ (_| | |  __/_| |_) | |_| |")
print(" |_| |_|\___|_|  |_| |_|_|___/\__|_|  \__,_|\__\___|\__, |_|\___(_) .__/ \__, |")
print("   ___   _____                                      |___/         |_|    |___/ ")
print("  / _ \ |___ /                                                                 ")
print(" | | | |  |_ \                                                                 ")
print(" | |_| | ___) |                                                                ")
print("  \___(_)____/                                                                 ")
print("                                   START HRY                                   ")
print("                                      ->start<-                                ")
print("                                                                               ")
print("                                 NASTAVENÍ HRY                                 ")
print("                                    ->nastaveni<-                              ")
print("                                                                               ")
print("                                   KONEC HRY                                   ")
print("                                      ->konec<-                                ")
print("                                                                               ")
print("                                                                               ")
print("                                                                               ")
print("                                                                               ")
print("                                                          BetovecIndustries2018")
menu = (input(""))

while True:
	if menu == "start":
		break
	elif menu == "nastaveni":
		while True:
			os.system('cls')
			print("")
			print("  _   _           _                        __                                  ")
			print(" | \ | | __ _ ___| |_ __ ___   _____ _ __ /_/                                  ")
			print(" |  \| |/ _` / __| __/ _` \ \ / / _ \ '_ \| |                                  ")
			print(" | |\  | (_| \__ \ || (_| |\ V /  __/ | | | |                                  ")
			print(" |_| \_|\__,_|___/\__\__,_| \_/ \___|_| |_|_|                                  ")
			print("                                                                               ")
			print("              ______                                                           ")
			print("             |HRÁČ 1|____________________                                      ")
			print("             |                           |                                     ")
			print("             | KREDITY TÝMU:             |                                     ")
			print("             |                           |                                     ")
			print("             | LÉKÁRNIČKY TÝMU:          |                                     ")
			print("             |___________________________|                                     ")
			print("              ______                                                           ")
			print("             |HRÁČ 2|____________________                                      ")
			print("             |                           |                                     ")
			print("             | KREDITY TÝMU:             |                                     ")
			print("             |                           |                                     ")
			print("             | LÉKÁRNIČKY TÝMU:          |                                     ")
			print("             |___________________________|                                     ")
			print("                                                                               ")
			print("     UPRAVIT ->upravit<-           KONEC ->konec<-                             ")
			print("                                                          BetovecIndustries2018")
			nastaveni = (input(""))
			if nastaveni == "upravit":
				print("")
				print("  _   _           _                        __                                  ")
				print(" | \ | | __ _ ___| |_ __ ___   _____ _ __ /_/                                  ")
				print(" |  \| |/ _` / __| __/ _` \ \ / / _ \ '_ \| |                                  ")
				print(" | |\  | (_| \__ \ || (_| |\ V /  __/ | | | |                                  ")
				print(" |_| \_|\__,_|___/\__\__,_| \_/ \___|_| |_|_|                                  ")
				print("                                                                               ")
				print("              ______                                                           ")
				print("             |HRÁČ 1|____________________                                      ")
				print("             |                           |                                     ")
				print("             | KREDITY TÝMU: ", modrytym.kredit,"            |                                     ")
				print("             |                           |                                     ")
				print("             | LÉKÁRNIČKY TÝMU: ", modrytym.lekarnicky,"         |                                     ")
				print("             |___________________________|                                     ")
				print("              ______                                                           ")
				print("             |HRÁČ 2|____________________                                      ")
				print("             |                           |                                     ")
				print("             | KREDITY TÝMU: ", cervenytym.kredit,"            |                                     ")
				print("             |                           |                                     ")
				print("             | LÉKÁRNIČKY TÝMU: ", cervenytym.kredit,"         |                                     ")
				print("             |___________________________|                                     ")
				print("                                                                               ")
				print("                                                          BetovecIndustries2018")
				nastaveni_modrytym_kredit = (input("Počet kreditů hráče 1: "))	
				if nastaveni_modrytym_kredit <= 10000:
					nastaveni_modrytym_kredit = modrytym.kredit
					os.system('cls')
					print("")
					print("  _   _           _                        __                                  ")
					print(" | \ | | __ _ ___| |_ __ ___   _____ _ __ /_/                                  ")
					print(" |  \| |/ _` / __| __/ _` \ \ / / _ \ '_ \| |                                  ")
					print(" | |\  | (_| \__ \ || (_| |\ V /  __/ | | | |                                  ")
					print(" |_| \_|\__,_|___/\__\__,_| \_/ \___|_| |_|_|                                  ")
					print("                                                                               ")
					print("              ______                                                           ")
					print("             |HRÁČ 1|____________________                                      ")
					print("             |                           |                                     ")
					print("             | KREDITY TÝMU: ", modrytym.kredit,"            |                                     ")
					print("             |                           |                                     ")
					print("             | LÉKÁRNIČKY TÝMU: ", modrytym.lekarnicky,"         |                                     ")
					print("             |___________________________|                                     ")
					print("              ______                                                           ")
					print("             |HRÁČ 2|____________________                                      ")
					print("             |                           |                                     ")
					print("             | KREDITY TÝMU: ", cervenytym.kredit,"            |                                     ")
					print("             |                           |                                     ")
					print("             | LÉKÁRNIČKY TÝMU: ", cervenytym.kredit,"         |                                     ")
					print("             |___________________________|                                     ")
					print("                                                                               ")
					print("                                                          BetovecIndustries2018")
					nastaveni_modrytym_lekarnicky = (input("Počet lékárniček hráče 1: "))
					if nastaveni_modrytym_lekarnicky <= 20:
						nastaveni_modrytym_lekarnicky = modrytym.lekarnicky
						os.system('cls')
						print("")
						print("  _   _           _                        __                                  ")
						print(" | \ | | __ _ ___| |_ __ ___   _____ _ __ /_/                                  ")
						print(" |  \| |/ _` / __| __/ _` \ \ / / _ \ '_ \| |                                  ")
						print(" | |\  | (_| \__ \ || (_| |\ V /  __/ | | | |                                  ")
						print(" |_| \_|\__,_|___/\__\__,_| \_/ \___|_| |_|_|                                  ")
						print("                                                                               ")
						print("              ______                                                           ")
						print("             |HRÁČ 1|____________________                                      ")
						print("             |                           |                                     ")
						print("             | KREDITY TÝMU: ", modrytym.kredit,"            |                                     ")
						print("             |                           |                                     ")
						print("             | LÉKÁRNIČKY TÝMU: ", modrytym.lekarnicky,"         |                                     ")
						print("             |___________________________|                                     ")
						print("              ______                                                           ")
						print("             |HRÁČ 2|____________________                                      ")
						print("             |                           |                                     ")
						print("             | KREDITY TÝMU: ", cervenytym.kredit,"            |                                     ")
						print("             |                           |                                     ")
						print("             | LÉKÁRNIČKY TÝMU: ", cervenytym.kredit,"         |                                     ")
						print("             |___________________________|                                     ")
						print("                                                                               ")
						print("                                                          BetovecIndustries2018")
						nastaveni_cervenytym_kredit = (input("Počet kreditů hráče 2: "))
						if nastaveni_cervenytym_kredit <= 10000:
							nastaveni_cervenytym_kredit = cervenytym.kredit
							os.system('cls')
							print("")
							print("  _   _           _                        __                                  ")
							print(" | \ | | __ _ ___| |_ __ ___   _____ _ __ /_/                                  ")
							print(" |  \| |/ _` / __| __/ _` \ \ / / _ \ '_ \| |                                  ")
							print(" | |\  | (_| \__ \ || (_| |\ V /  __/ | | | |                                  ")
							print(" |_| \_|\__,_|___/\__\__,_| \_/ \___|_| |_|_|                                  ")
							print("                                                                               ")
							print("              ______                                                           ")
							print("             |HRÁČ 1|____________________                                      ")
							print("             |                           |                                     ")
							print("             | KREDITY TÝMU: ", modrytym.kredit,"            |                                     ")
							print("             |                           |                                     ")
							print("             | LÉKÁRNIČKY TÝMU: ", modrytym.lekarnicky,"         |                                     ")
							print("             |___________________________|                                     ")
							print("              ______                                                           ")
							print("             |HRÁČ 2|____________________                                      ")
							print("             |                           |                                     ")
							print("             | KREDITY TÝMU: ", cervenytym.kredit,"            |                                     ")
							print("             |                           |                                     ")
							print("             | LÉKÁRNIČKY TÝMU: ", cervenytym.kredit,"         |                                     ")
							print("             |___________________________|                                     ")
							print("                                                                               ")
							print("                                                          BetovecIndustries2018")
							nastaveni_cervenytym_lekarnicky = (input("Počet lékárniček hráče 2: "))
							if nastaveni_cervenytym_lekarnicky <= 20:
								nastaveni_cervenytym_lekarnicky = cervenytym.kredit
							else:
								os.system('cls')
								print("Neplatná volba")
								time.sleep(1)
								os.system('cls')			
						else:
							os.system('cls')
							print("Neplatná volba")
							time.sleep(1)
							os.system('cls')	
					else:	
						os.system('cls')
						print("Neplatná volba")
						time.sleep(1)
						os.system('cls')
				else:
					os.system('cls')
					print("Neplatná volba")
					time.sleep(1)
					os.system('cls')	
			else:
				break	
	else:
		menu_konechry = 1			


#######



while True:
	if menu == "start":
		break
	elif menu == "nastaveni":
		while True:
			os.system('cls')
			print("")
			print("  _   _           _                        __                                  ")
			print(" | \ | | __ _ ___| |_ __ ___   _____ _ __ /_/                                  ")
			print(" |  \| |/ _` / __| __/ _` \ \ / / _ \ '_ \| |                                  ")
			print(" | |\  | (_| \__ \ || (_| |\ V /  __/ | | | |                                  ")
			print(" |_| \_|\__,_|___/\__\__,_| \_/ \___|_| |_|_|                                  ")
			print("                                                                               ")
			print("              ______                                                           ")
			print("             |HRÁČ 1|____________________                                      ")
			print("             |                           |                                     ")
			print("             | KREDITY TÝMU: ", modrytym.kredit," ")
			print("             |                           |                                     ")
			print("             | LÉKÁRNIČKY TÝMU: ", modrytym.lekarnicky," ")
			print("             |___________________________|                                     ")
			print("              ______                                                           ")
			print("             |HRÁČ 2|____________________                                      ")
			print("             |                           |                                     ")
			print("             | KREDITY TÝMU: ", cervenytym.kredit," ")
			print("             |                           |                                     ")
			print("             | LÉKÁRNIČKY TÝMU: ", cervenytym.kredit," ")
			print("             |___________________________|                                     ")
			print("                                                                               ")
			print("     UPRAVIT ->upravit<-           KONEC ->konec<-                             ")
			print("                                                          BetovecIndustries2018")
			nastaveni = (input(""))
			if nastaveni == "upravit":
				os.system('cls')
				print("")
				print("  _   _           _                        __                                  ")
				print(" | \ | | __ _ ___| |_ __ ___   _____ _ __ /_/                                  ")
				print(" |  \| |/ _` / __| __/ _` \ \ / / _ \ '_ \| |                                  ")
				print(" | |\  | (_| \__ \ || (_| |\ V /  __/ | | | |                                  ")
				print(" |_| \_|\__,_|___/\__\__,_| \_/ \___|_| |_|_|                                  ")
				print("                                                                               ")
				print("              ______                                                           ")
				print("             |HRÁČ 1|____________________                                      ")
				print("             |                           |                                     ")
				print("             | KREDITY TÝMU: ", modrytym.kredit," ")
				print("             |                           |                                     ")
				print("             | LÉKÁRNIČKY TÝMU: ", modrytym.lekarnicky," ")
				print("             |___________________________|                                     ")
				print("              ______                                                           ")
				print("             |HRÁČ 2|____________________                                      ")
				print("             |                           |                                     ")
				print("             | KREDITY TÝMU: ", cervenytym.kredit," ")
				print("             |                           |                                     ")
				print("             | LÉKÁRNIČKY TÝMU: ", cervenytym.kredit," ")
				print("             |___________________________|                                     ")
				print("                                                                               ")
				print("                                                          BetovecIndustries2018")
				nastaveni_modrytym_kredit = (input("Počet kreditů hráče 1: "))	
				if nastaveni_modrytym_kredit <= "10000":
					nastaveni_modrytym_kredit = modrytym.kredit
					os.system('cls')
					print("")
					print("  _   _           _                        __                                  ")
					print(" | \ | | __ _ ___| |_ __ ___   _____ _ __ /_/                                  ")
					print(" |  \| |/ _` / __| __/ _` \ \ / / _ \ '_ \| |                                  ")
					print(" | |\  | (_| \__ \ || (_| |\ V /  __/ | | | |                                  ")
					print(" |_| \_|\__,_|___/\__\__,_| \_/ \___|_| |_|_|                                  ")
					print("                                                                               ")
					print("              ______                                                           ")
					print("             |HRÁČ 1|____________________                                      ")
					print("             |                           |                                     ")
					print("             | KREDITY TÝMU: ", modrytym.kredit," ")
					print("             |                           |                                     ")
					print("             | LÉKÁRNIČKY TÝMU: ", modrytym.lekarnicky," ")
					print("             |___________________________|                                     ")
					print("              ______                                                           ")
					print("             |HRÁČ 2|____________________                                      ")
					print("             |                           |                                     ")
					print("             | KREDITY TÝMU: ", cervenytym.kredit," ")
					print("             |                           |                                     ")
					print("             | LÉKÁRNIČKY TÝMU: ", cervenytym.kredit," ")
					print("             |___________________________|                                     ")
					print("                                                                               ")
					print("                                                          BetovecIndustries2018")
					nastaveni_modrytym_lekarnicky = (input("Počet lékárniček hráče 1: "))
					if nastaveni_modrytym_lekarnicky <= "20":
						nastaveni_modrytym_lekarnicky = modrytym.lekarnicky
						os.system('cls')
						print("")
						print("  _   _           _                        __                                  ")
						print(" | \ | | __ _ ___| |_ __ ___   _____ _ __ /_/                                  ")
						print(" |  \| |/ _` / __| __/ _` \ \ / / _ \ '_ \| |                                  ")
						print(" | |\  | (_| \__ \ || (_| |\ V /  __/ | | | |                                  ")
						print(" |_| \_|\__,_|___/\__\__,_| \_/ \___|_| |_|_|                                  ")
						print("                                                                               ")
						print("              ______                                                           ")
						print("             |HRÁČ 1|____________________                                      ")
						print("             |                           |                                     ")
						print("             | KREDITY TÝMU: ", modrytym.kredit," ")
						print("             |                           |                                     ")
						print("             | LÉKÁRNIČKY TÝMU: ", modrytym.lekarnicky," ")
						print("             |___________________________|                                     ")
						print("              ______                                                           ")
						print("             |HRÁČ 2|____________________                                      ")
						print("             |                           |                                     ")
						print("             | KREDITY TÝMU: ", cervenytym.kredit," ")
						print("             |                           |                                     ")
						print("             | LÉKÁRNIČKY TÝMU: ", cervenytym.kredit," ")
						print("             |___________________________|                                     ")
						print("                                                                               ")
						print("                                                          BetovecIndustries2018")
						nastaveni_cervenytym_kredit = (input("Počet kreditů hráče 2: "))
						if nastaveni_cervenytym_kredit <= "10000":
							nastaveni_cervenytym_kredit = cervenytym.kredit
							os.system('cls')
							print("")
							print("  _   _           _                        __                                  ")
							print(" | \ | | __ _ ___| |_ __ ___   _____ _ __ /_/                                  ")
							print(" |  \| |/ _` / __| __/ _` \ \ / / _ \ '_ \| |                                  ")
							print(" | |\  | (_| \__ \ || (_| |\ V /  __/ | | | |                                  ")
							print(" |_| \_|\__,_|___/\__\__,_| \_/ \___|_| |_|_|                                  ")
							print("                                                                               ")
							print("              ______                                                           ")
							print("             |HRÁČ 1|____________________                                      ")
							print("             |                           |                                     ")
							print("             | KREDITY TÝMU: ", modrytym.kredit," ")
							print("             |                           |                                     ")
							print("             | LÉKÁRNIČKY TÝMU: ", modrytym.lekarnicky," ")
							print("             |___________________________|                                     ")
							print("              ______                                                           ")
							print("             |HRÁČ 2|____________________                                      ")
							print("             |                           |                                     ")
							print("             | KREDITY TÝMU: ", cervenytym.kredit," ")
							print("             |                           |                                     ")
							print("             | LÉKÁRNIČKY TÝMU: ", cervenytym.kredit," ")
							print("             |___________________________|                                     ")
							print("                                                                               ")
							print("                                                          BetovecIndustries2018")
							nastaveni_cervenytym_lekarnicky = (input("Počet lékárniček hráče 2: "))
							if nastaveni_cervenytym_lekarnicky <= "20":
								nastaveni_cervenytym_lekarnicky = cervenytym.kredit
							else:
								os.system('cls')
								print("Neplatná volba")
								time.sleep(1)
								os.system('cls')			
						else:
							os.system('cls')
							print("Neplatná volba")
							time.sleep(1)
							os.system('cls')	
					else:	
						os.system('cls')
						print("Neplatná volba")
						time.sleep(1)
						os.system('cls')
				else:
					os.system('cls')
					print("Neplatná volba")
					time.sleep(1)
					os.system('cls')		



		






