print("_______________________________________________________________________________")
print("Právě hraje hráč: Pavel           Kredity: 1000 $         Lékárničky: 2        ")
print("_______________________________________________________________________________")
print("|                |                                                             ")
print("| Pozice: 1.     |                                             4.   O O O O O  ")
print("| Vitalita:      |   .---._                                           _.---.   ")
print("|  O O O O O     |   :   : \                                         / :   :   ")
print("| Zbraň: MARAKOV |   ´O-O-O/                                         \O-O-O´   ")
print("|                |                                                             ")
print("| Pozice: 2.     |                                             5.   O O O O O  ")
print("| Vitalita:      |   .---._                                           _.---.   ")
print("|  O O O O O     |   :   : \                                         / :   :   ")
print("| Zbraň: MARAKOV |   ´O-O-O/                                         \O-O-O´   ")
print("|                |                                                             ")
print("| Pozice: 3.     |                                             6.   O O O O O  ")
print("| Vitalita:      |   .---._                                           _.---.   ")
print("|  O O O O O     |   :   : \                                         / :   :   ")
print("| Zbraň: MARAKOV |   ´O-O-O/                                         \O-O-O´   ")