print("|SKÓRE| Název týmu: Pavel                                                      ")
print("|  3  | Kredity: 1000$     Lékárničky: 1                                       ")
print("|____ |________________________________________________________________________")
print("|Pozice: 1.    |                                                              |")
print("|Vitalita:     | .---._                                              .---._   |")
print("| O O O O O    | :   : \                                             :   : \  |")
print("|Zbraň: MARAKOV| ´O-O-O/                                             ´O-O-O/  |")
print("|              |                                                              |")
print("|Pozice: 2.    |                                                              |")
print("|Vitalita:     | .---._                                              .---._   |")
print("| O O O O O    | :   : \                                             :   : \  |")
print("|Zbraň: MARAKOV| ´O-O-O/                                             ´O-O-O/  |")
print("|              |                                                              |")
print("|Pozice: 3.    |                                                              |")
print("|Vitalita:     | .---._                                              .---._   |")
print("| O O O O O    | :   : \                                             :   : \  |")
print("|Zbraň: MARAKOV| ´O-O-O/                                             ´O-O-O/  |")

print(" ________ ")
print("|.---._  |")
print("|:   : \ |")
print("|´O-O-O/ |")
print("|________|")

print(" __ ")
print("|  |")
print("|  |")
print("|__|")
