print(" _   _   _   _                                                 _   _   _   _ ")
print("| |_| |_| |_| |                                               | |_| |_| |_| |")
print("|             |                                               |             |")
print("|  ", "postavas", " |", " ", "Pozice:", "1.", "                           ", "4.", " ", "| ", "postavas", "  |")
print("|  ", "postavas", " |", " ", "Vitalita:", "▄ ▄ ▄    ", "           ", "    ▄ ▄ ▄", " ", "| ", "postavas", "  |")
print("|  ", "postavas", " |", " ", "Zbraň:", "MARAKOV", "                  ", "MARAKOV", " ", "| ", "postavas", "  |")
print("|             |                                               |             |")
print("|             |                                               |             |")
print("|  ", "postavas", " |", " ", "Pozice:", "2.", "                           ", "5.", " ", "| ", "postavas", "  |")
print("|  ", "postavas", " |", " ", "Vitalita:", "▄ ▄ ▄    ", "           ", "    ▄ ▄ ▄", " ", "| ", "postavas", "  |")
print("|  ", "postavas", " |", " ", "Zbraň:", "MARAKOV", "                  ", "MARAKOV", " ", "| ", "postavas", "  |")
print("|             |                                               |             |")
print("|             |                                               |             |")
print("|  ", "postavas", " |", " ", "Pozice:", "3.", "                           ", "6.", " ", "| ", "postavas", "  |")
print("|  ", "postavas", " |", " ", "Vitalita:", "▄ ▄ ▄    ", "           ", "    ▄ ▄ ▄", " ", "| ", "postavas", "  |")
print("|  ", "postavas", " |", " ", "Zbraň:", "MARAKOV", "                  ", "MARAKOV", " ", "| ", "postavas", "  |")

input()